/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IntAdd */

#ifndef _Included_IntAdd
#define _Included_IntAdd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IntAdd
 * Method:    print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_IntAdd_print
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
