//Copyright (C) 2018 Cornell University

package jlang.runtime;

// Wraps the Java entry point in a try-catch block so that we can
// report uncaught exceptions to the client.
class MainWrapper {

    // This native method is generated by JLang when it encounters
    // the main method in the client program.
    static native void main(String[] args);

    static void runMain(String[] args) {
        // TODO: Print stack trace.
        main(args);
    }
}
