/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeTest */

#ifndef _Included_NativeTest
#define _Included_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeTest
 * Method:    getNativeStringTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeTest_getNativeStringTest
  (JNIEnv *, jclass);

/*
* Class:     NativeTest_NativeTestInner
* Method:    getNativeInnerStringTest
* Signature: ()Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_NativeTest_00024NativeTestInner_getNativeInnerStringTest
(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
