/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_misc_Unsafe */

#ifndef _Included_sun_misc_Unsafe
#define _Included_sun_misc_Unsafe
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_misc_Unsafe_INVALID_FIELD_OFFSET
#define sun_misc_Unsafe_INVALID_FIELD_OFFSET -1L
/*
 * Class:     sun_misc_Unsafe
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_registerNatives
  (JNIEnv *, jclass);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getInt
 * Signature: (Ljava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_getInt__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putInt
 * Signature: (Ljava/lang/Object;JI)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putInt__Ljava_lang_Object_2JI
  (JNIEnv *, jobject, jobject, jlong, jint);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getObject
 * Signature: (Ljava/lang/Object;J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_sun_misc_Unsafe_getObject
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putObject
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putObject
  (JNIEnv *, jobject, jobject, jlong, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getBoolean
 * Signature: (Ljava/lang/Object;J)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_misc_Unsafe_getBoolean
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putBoolean
 * Signature: (Ljava/lang/Object;JZ)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putBoolean
  (JNIEnv *, jobject, jobject, jlong, jboolean);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getByte
 * Signature: (Ljava/lang/Object;J)B
 */
JNIEXPORT jbyte JNICALL Java_sun_misc_Unsafe_getByte__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putByte
 * Signature: (Ljava/lang/Object;JB)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putByte__Ljava_lang_Object_2JB
  (JNIEnv *, jobject, jobject, jlong, jbyte);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getShort
 * Signature: (Ljava/lang/Object;J)S
 */
JNIEXPORT jshort JNICALL Java_sun_misc_Unsafe_getShort__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putShort
 * Signature: (Ljava/lang/Object;JS)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putShort__Ljava_lang_Object_2JS
  (JNIEnv *, jobject, jobject, jlong, jshort);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getChar
 * Signature: (Ljava/lang/Object;J)C
 */
JNIEXPORT jchar JNICALL Java_sun_misc_Unsafe_getChar__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putChar
 * Signature: (Ljava/lang/Object;JC)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putChar__Ljava_lang_Object_2JC
  (JNIEnv *, jobject, jobject, jlong, jchar);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getLong
 * Signature: (Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_getLong__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putLong
 * Signature: (Ljava/lang/Object;JJ)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putLong__Ljava_lang_Object_2JJ
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getFloat
 * Signature: (Ljava/lang/Object;J)F
 */
JNIEXPORT jfloat JNICALL Java_sun_misc_Unsafe_getFloat__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putFloat
 * Signature: (Ljava/lang/Object;JF)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putFloat__Ljava_lang_Object_2JF
  (JNIEnv *, jobject, jobject, jlong, jfloat);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getDouble
 * Signature: (Ljava/lang/Object;J)D
 */
JNIEXPORT jdouble JNICALL Java_sun_misc_Unsafe_getDouble__Ljava_lang_Object_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putDouble
 * Signature: (Ljava/lang/Object;JD)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putDouble__Ljava_lang_Object_2JD
  (JNIEnv *, jobject, jobject, jlong, jdouble);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_sun_misc_Unsafe_getByte__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putByte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putByte__JB
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_sun_misc_Unsafe_getShort__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putShort
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putShort__JS
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getChar
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_sun_misc_Unsafe_getChar__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putChar
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putChar__JC
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_getInt__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putInt__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_getLong__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putLong
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putLong__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_sun_misc_Unsafe_getFloat__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putFloat
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putFloat__JF
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_sun_misc_Unsafe_getDouble__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putDouble
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putDouble__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_getAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putAddress
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putAddress
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_allocateMemory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    reallocateMemory
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_reallocateMemory
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    setMemory
 * Signature: (Ljava/lang/Object;JJB)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_setMemory
  (JNIEnv *, jobject, jobject, jlong, jlong, jbyte);

/*
 * Class:     sun_misc_Unsafe
 * Method:    copyMemory
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;JJ)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_copyMemory
  (JNIEnv *, jobject, jobject, jlong, jobject, jlong, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_freeMemory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    staticFieldOffset
 * Signature: (Ljava/lang/reflect/Field;)J
 */
JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_staticFieldOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    objectFieldOffset
 * Signature: (Ljava/lang/reflect/Field;)J
 */
JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_objectFieldOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    staticFieldBase
 * Signature: (Ljava/lang/reflect/Field;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_sun_misc_Unsafe_staticFieldBase
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    shouldBeInitialized
 * Signature: (Ljava/lang/Class;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_misc_Unsafe_shouldBeInitialized
  (JNIEnv *, jobject, jclass);

/*
 * Class:     sun_misc_Unsafe
 * Method:    ensureClassInitialized
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_ensureClassInitialized
  (JNIEnv *, jobject, jclass);

/*
 * Class:     sun_misc_Unsafe
 * Method:    arrayBaseOffset
 * Signature: (Ljava/lang/Class;)I
 */
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_arrayBaseOffset
  (JNIEnv *, jobject, jclass);

/*
 * Class:     sun_misc_Unsafe
 * Method:    arrayIndexScale
 * Signature: (Ljava/lang/Class;)I
 */
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_arrayIndexScale
  (JNIEnv *, jobject, jclass);

/*
 * Class:     sun_misc_Unsafe
 * Method:    addressSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_addressSize
  (JNIEnv *, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    pageSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_pageSize
  (JNIEnv *, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    defineClass
 * Signature: (Ljava/lang/String;[BIILjava/lang/ClassLoader;Ljava/security/ProtectionDomain;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_sun_misc_Unsafe_defineClass
  (JNIEnv *, jobject, jstring, jbyteArray, jint, jint, jobject, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    defineAnonymousClass
 * Signature: (Ljava/lang/Class;[B[Ljava/lang/Object;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_sun_misc_Unsafe_defineAnonymousClass
  (JNIEnv *, jobject, jclass, jbyteArray, jobjectArray);

/*
 * Class:     sun_misc_Unsafe
 * Method:    allocateInstance
 * Signature: (Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_sun_misc_Unsafe_allocateInstance
  (JNIEnv *, jobject, jclass);

/*
 * Class:     sun_misc_Unsafe
 * Method:    monitorEnter
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_monitorEnter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    monitorExit
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_monitorExit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    tryMonitorEnter
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_misc_Unsafe_tryMonitorEnter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    throwException
 * Signature: (Ljava/lang/Throwable;)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_throwException
  (JNIEnv *, jobject, jthrowable);

/*
 * Class:     sun_misc_Unsafe
 * Method:    compareAndSwapObject
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_misc_Unsafe_compareAndSwapObject
  (JNIEnv *, jobject, jobject, jlong, jobject, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    compareAndSwapInt
 * Signature: (Ljava/lang/Object;JII)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_misc_Unsafe_compareAndSwapInt
  (JNIEnv *, jobject, jobject, jlong, jint, jint);

/*
 * Class:     sun_misc_Unsafe
 * Method:    compareAndSwapLong
 * Signature: (Ljava/lang/Object;JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_misc_Unsafe_compareAndSwapLong
  (JNIEnv *, jobject, jobject, jlong, jlong, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getObjectVolatile
 * Signature: (Ljava/lang/Object;J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_sun_misc_Unsafe_getObjectVolatile
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putObjectVolatile
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putObjectVolatile
  (JNIEnv *, jobject, jobject, jlong, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getIntVolatile
 * Signature: (Ljava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_getIntVolatile
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putIntVolatile
 * Signature: (Ljava/lang/Object;JI)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putIntVolatile
  (JNIEnv *, jobject, jobject, jlong, jint);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getBooleanVolatile
 * Signature: (Ljava/lang/Object;J)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_misc_Unsafe_getBooleanVolatile
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putBooleanVolatile
 * Signature: (Ljava/lang/Object;JZ)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putBooleanVolatile
  (JNIEnv *, jobject, jobject, jlong, jboolean);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getByteVolatile
 * Signature: (Ljava/lang/Object;J)B
 */
JNIEXPORT jbyte JNICALL Java_sun_misc_Unsafe_getByteVolatile
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putByteVolatile
 * Signature: (Ljava/lang/Object;JB)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putByteVolatile
  (JNIEnv *, jobject, jobject, jlong, jbyte);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getShortVolatile
 * Signature: (Ljava/lang/Object;J)S
 */
JNIEXPORT jshort JNICALL Java_sun_misc_Unsafe_getShortVolatile
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putShortVolatile
 * Signature: (Ljava/lang/Object;JS)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putShortVolatile
  (JNIEnv *, jobject, jobject, jlong, jshort);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getCharVolatile
 * Signature: (Ljava/lang/Object;J)C
 */
JNIEXPORT jchar JNICALL Java_sun_misc_Unsafe_getCharVolatile
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putCharVolatile
 * Signature: (Ljava/lang/Object;JC)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putCharVolatile
  (JNIEnv *, jobject, jobject, jlong, jchar);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getLongVolatile
 * Signature: (Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_getLongVolatile
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putLongVolatile
 * Signature: (Ljava/lang/Object;JJ)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putLongVolatile
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getFloatVolatile
 * Signature: (Ljava/lang/Object;J)F
 */
JNIEXPORT jfloat JNICALL Java_sun_misc_Unsafe_getFloatVolatile
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putFloatVolatile
 * Signature: (Ljava/lang/Object;JF)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putFloatVolatile
  (JNIEnv *, jobject, jobject, jlong, jfloat);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getDoubleVolatile
 * Signature: (Ljava/lang/Object;J)D
 */
JNIEXPORT jdouble JNICALL Java_sun_misc_Unsafe_getDoubleVolatile
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putDoubleVolatile
 * Signature: (Ljava/lang/Object;JD)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putDoubleVolatile
  (JNIEnv *, jobject, jobject, jlong, jdouble);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putOrderedObject
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putOrderedObject
  (JNIEnv *, jobject, jobject, jlong, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putOrderedInt
 * Signature: (Ljava/lang/Object;JI)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putOrderedInt
  (JNIEnv *, jobject, jobject, jlong, jint);

/*
 * Class:     sun_misc_Unsafe
 * Method:    putOrderedLong
 * Signature: (Ljava/lang/Object;JJ)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putOrderedLong
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    unpark
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_unpark
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    park
 * Signature: (ZJ)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_park
  (JNIEnv *, jobject, jboolean, jlong);

/*
 * Class:     sun_misc_Unsafe
 * Method:    getLoadAverage
 * Signature: ([DI)I
 */
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_getLoadAverage
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     sun_misc_Unsafe
 * Method:    loadFence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_loadFence
  (JNIEnv *, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    storeFence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_storeFence
  (JNIEnv *, jobject);

/*
 * Class:     sun_misc_Unsafe
 * Method:    fullFence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_fullFence
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
