
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150325 (SVN rev 63)
//----------------------------------------------------

package miniparser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int READ = 11;
  public static final int IDENT = 21;
  public static final int SEMICOLON = 2;
  public static final int ELSE = 9;
  public static final int STRINGCONST = 22;
  public static final int COMP = 18;
  public static final int WHILE = 10;
  public static final int END = 7;
  public static final int INTCONST = 20;
  public static final int BBINOP = 19;
  public static final int IF = 8;
  public static final int WRITE = 12;
  public static final int BEGIN = 6;
  public static final int TYPE = 15;
  public static final int COMMA = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int BUNOP = 13;
  public static final int ASSIGN = 14;
  public static final int RPAR = 5;
  public static final int BINOP = 16;
  public static final int LPAR = 4;
  public static final int BOOLCONST = 23;
  public static final int UNOP = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "COMMA",
  "LPAR",
  "RPAR",
  "BEGIN",
  "END",
  "IF",
  "ELSE",
  "WHILE",
  "READ",
  "WRITE",
  "BUNOP",
  "ASSIGN",
  "TYPE",
  "BINOP",
  "UNOP",
  "COMP",
  "BBINOP",
  "INTCONST",
  "IDENT",
  "STRINGCONST",
  "BOOLCONST"
  };
}

