OUT := out
LL := $(shell find $(OUT) -name "*.ll")
OBJ := $(LL:%.ll=%.o)

all: $(OBJ)
.PHONY: all

$(OBJ): %.o: %.ll $(OUT)/llstamp
	@echo "Compiling $<"
	@clang++ -Wno-override-module -fPIC -c -o $@ $<
